Arch Migrator
conda-forge/popt-feedstock pull request #10
Opened 2019-08-28 21:18 UTC by chrisburr

See #9

2019-08-28 21:18 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2019-08-29 03:05 UTC, sodre commented
@chrisburr, is popt arch migrator ready to merge?

2019-08-29 05:56 UTC, chrisburr commented
@sodre yes it is.

#9 can then be closed.

2019-08-29 13:43 UTC, sodre requested changes
Please move them

2019-08-29 13:43 UTC, sodre commented on recipe/build.sh
> +curl -L 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' > config.sub
Can we convert these two curls into entries in the source section with sha256sums?

Also, shouldn't we be pulling the config{.guess,sub} of the same version of popt? In your URL it looks like we are downloading from the master branch.

2019-08-29 13:49 UTC, chrisburr commented on recipe/build.sh
> +curl -L 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' > config.sub
Yes, sorry I meant to do that and forgot.

The error message I got without them suggested to use these URLS and the master branch.

2019-08-29 13:53 UTC, sodre commented on recipe/build.sh
> +curl -L 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' > config.sub
Ahh, I see. The files exist already. Shouldn't we do a patch instead in that case?

2019-08-29 14:11 UTC, chrisburr commented on recipe/build.sh
> +curl -L 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' > config.sub
I've committed a suggested approach which I think is cleaner as it's easier to update if required. If you'd prefer a patch let me know and I'll do it that way.

2019-08-29 14:20 UTC, sodre commented on recipe/build.sh
> +curl -L 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD' > config.sub
I like your solution better 👍

2019-08-29 14:32 UTC, merged

2019-08-29 14:35 UTC, chrisburr commented
Thanks for the prompt review/merge! 🍰